[package]
name = "bf-jit"
version = "0.1.0"
authors = ["liangyongrui <liangyongrui@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dynasmrt = "1.0"
thiserror = "1.0"
